version: '3.4'

services:
  routesoptimizer:
    image: ${DOCKER_REGISTRY-}routesoptimizer
    build:
      context: .
      dockerfile: RoutesOptimizer/Dockerfile
    ports:
    - '4015:8081'

  routesoptimizer.client:
    image: ${DOCKER_REGISTRY-}routesoptimizer.client
    build:
      context: RoutesOptimizer.Client
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
       - routesoptimizer

